nelmio_api_doc:
    documentation:
        info:
            title: Musical
            description: An ear training web service
            version: 0.1
    areas:
        path_patterns:
            - ^/api(?!/documentation$)
