version: '3'
services:
  php:
    build: docker-compose/php
    ports:
      - 9001:9000
    volumes:
      - .:/var/www/symfony:cached
  nginx:
    build: docker-compose/nginx
    ports:
      - 81:80
    volumes:
      - .:/var/www/symfony
      - ./docker-compose/.data/nginx/logs/:/var/log/nginx
    links:
      - php
