version: '3'
services:
  php:
    build: docker-compose/php
    volumes:
      - .:/var/www/symfony
      - ./docker-compose/php/php.ini:/usr/local/etc/php/php.ini
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - .:/var/www/symfony
      - ./docker-compose/.data/nginx/logs/:/var/log/nginx
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
